---

- name: update system
  hosts: all
  sudo: yes
  tasks:
    - include: tasks/apt-update.yml

- name: install system dependencies
  hosts: all
  roles:
    - role: apt_get_install
      # Required packages
      # * acl is required for the ansible acl module.
      # * essentially everything that gets built requires build-essential.
      items:
        - acl
        - build-essential

- name: install hubot
  hosts: all
  sudo: yes
  gather_facts: yes
  vars_files:
    - "vars/adapter.yml"
  vars:
    # merge hubot_env in group_vars/all.yml and vars/adapter.yml
    hubot_env: "{{ default_hubot_env.update(adapter_hubot_env) }}{{ default_hubot_env }}"
  roles:
    - role: brianshumate.hubot
    - role: custom_hubot_scripts
      hubot_tz: 'America/Chicago'
